name: build

# https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/adding-a-workflow-status-badge

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
#    defaults:
#      run:
#        shell: bash
#        working-directory: $GITHUB_WORKSPACE

    steps:
      - uses: actions/checkout@v2
      #      https://stackoverflow.com/questions/56726429/how-to-run-multiple-commands-in-one-github-actions-docker

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

#      - name: Update system dependencies
#        run: |
#          sudo apt-get update
#          sudo apt-get install -y curl unzip zip wget

      - name: Install sdkman
        run: |
          bash -c "curl -s "https://get.sdkman.io" | bash"
          source "/home/runner/.sdkman/bin/sdkman-init.sh"

      - name: Install kotlin
        run: |
          source "/home/runner/.sdkman/bin/sdkman-init.sh"
          sdk install kotlin 1.6.0

      - name: Install gradle
        run: |
          source "/home/runner/.sdkman/bin/sdkman-init.sh"
          sdk install gradle 7.2


      # https://stackoverflow.com/questions/50104666/gradle-difference-between-test-and-check
      - name: Build and test with Gradle
#        working-directory: $GITHUB_WORKSPACE
        run: |
          echo  $GITHUB_WORKSPACE
          chmod +x gradlew
          ./gradlew clean check --stacktrace --info


      - name: Build kscript
        run: ./gradlew assemble

      - name: Install assert.sh
        run: |
          wget https://raw.github.com/lehmannro/assert.sh/v1.1/assert.sh
          chmod +x assert.sh

      # https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#adding-a-system-path
      - name: Update PATH to include kscrript
        run: echo "${GITHUB_WORKSPACE}/build/libs" >> $GITHUB_PATH

      - run: which kscript

      - name: Print --version
        run: |
          source "/home/runner/.sdkman/bin/sdkman-init.sh"
          kscript --version

      - name: Create mock idea executable
        run: |
          touch idea
          chmod +x idea
          echo "${PWD}" >> $GITHUB_PATH

      - name: Run tests
        run: |
          source "/home/runner/.sdkman/bin/sdkman-init.sh"
          export KSCRIPT_HOME="$GITHUB_WORKSPACE"
          ./test/test_suite.sh
